[package]
name = "inventory"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
database = { path = "../database" }

diesel = { workspace = true }
actix-web = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }

log = { workspace = true }

# OpenAPI v3 spec generator and embedded swagger UI
utoipa = { workspace = true }
