//! ==============================================================================
//! Diesel Database Models for Catalog
//! ==============================================================================
//! These structs represent the raw shape of data coming out of or going into
//! the `catalog.products` table in PostgreSQL.
//! ==============================================================================

use chrono::{DateTime, Utc};
use diesel::prelude::*;
use serde::Serialize;
use uuid::Uuid;

// Import the table definition generated by diesel-cli
use database::schema::catalog::products;

/// Represents a row read directly from the `catalog.products` table.
///
/// Derived traits explained:
/// - `Queryable`: Allows Diesel to map the columns of a SELECT query into this struct.
///   (Field order and types MUST match the table definition in schema.rs exactly).
/// - `Selectable`: Enables using `Product::as_select()` for type-safe column projection.
/// - `Identifiable`: Associates this struct with its primary key (`id`), simplifying updates.
/// - `Serialize`: Allows serializing the entity to JSON if needed for read responses.
#[derive(Debug, Clone, Queryable, Selectable, Identifiable, Serialize)]
#[diesel(table_name = products)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct Product {
    pub id: Uuid,
    pub sku: String,
    pub title: String,
    pub description: Option<String>,
    pub price_cents: i64,
    pub is_active: bool,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

/// Represents the data required to INSERT a new row into `catalog.products`.
///
/// Notice what is missing:
/// - `id`: Handled by Postgres default `uuid_generate_v4()`.
/// - `created_at` / `updated_at`: Handled by Postgres `DEFAULT NOW()`.
///
/// Derived traits:
/// - `Insertable`: Allows passing `&NewProduct` into `diesel::insert_into(products::table)`.
#[derive(Debug, Insertable)]
#[diesel(table_name = products)]
pub struct NewProduct<'a> {
    pub sku: &'a str,
    pub title: &'a str,
    pub description: Option<&'a str>,
    pub price_cents: i64,
    pub is_active: bool,
}

/// Represents the data for updating an existing product via `AsChangeset`.
///
/// All fields are `Option<T>`. When compiled with `#[diesel(treat_none_as_null = false)]`,
/// any `None` field is omitted from the generated SQL `UPDATE ... SET` clause.
#[derive(Debug, Default, AsChangeset)]
#[diesel(table_name = products)]
#[diesel(treat_none_as_null = false)]
pub struct UpdateProduct<'a> {
    pub title: Option<&'a str>,
    pub description: Option<Option<&'a str>>, // Outer Option: update requested? Inner Option: set to NULL?
    pub price_cents: Option<i64>,
    pub is_active: Option<bool>,
    pub updated_at: Option<DateTime<Utc>>,
}
